title: CTM Building Blocks
summary: Common library of useful classess

copyright: Copyright (c) 2014 ComparetheMarket
licenseUrl: http://www.comparethemarket.com
projectUrl: https://github.com/ComparetheMarket/CTM.Common.BuildingBlocks
iconUrl: http://www.comparethemarket.com/favicon.ico
tags:
 - buildingblocks